# Generated by Django 5.0.2 on 2024-02-27 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Logs.entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry',
            field=models.CharField(max_length=200),
        ),
    ]
