# Generated by Django 5.0.2 on 2024-02-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0003_remove_entry_entry_entry_entries_alter_topic_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='entry',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
