# Generated by Django 5.0.2 on 2024-02-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0005_remove_entry_entries_remove_topic_entry_entry_entry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='entries',
        ),
        migrations.AddField(
            model_name='topic',
            name='entry',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Entrys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Logs.topic')),
            ],
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
