# Generated by Django 5.0.2 on 2024-02-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0006_remove_topic_entries_topic_entry_entrys_delete_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrys',
            old_name='entries',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='entry',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_name',
        ),
        migrations.AddField(
            model_name='entrys',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
